### ISSUE TITLE
feature request: add ability to point to arbitrary URL for other databases

### ISSUE THREAD

**Issue by cdshaffer** [SEA-PHAGES/pdm_utils#11]
Would be nice to use pdb_utils to manage all databases. So the ability to point to different servers with different databases would be nice. Might need to document the need for both the .sql and .version files. 

On the other hand, since running get_db is being done by a person, then I think a `get_db` should fetch and install the database irrespective of version, i.e. it is how one would do a force update. Maybe a different routine like `get_db update` could be implemented which could check the version file and only update if a new version is on the remote server.

**Comment by tmavrich** [comment]
Currently, get_db always performs a force install and overwrites the existing database, but it definitely makes sense to implement a version check at some point.

For now, I've added custom URL functionality to access databases from other servers. I've also added the ability the choose whether or not the version file should be downloaded; in the short-term, a patch on the end-user side could be implemented to compare versions and decide whether or not to install:

`python3 -m pdm_utils get_db Actinobacteriophage server -u <custom URL> -v`

**Comment by tmavrich** [comment]
I've also generalized the push pipeline, so that databases can be uploaded to any server, instead of the default production server.

`python3 -m pdm_utils push -f Actinobacteriophage.sql -s <server host name> -rd <absolute path to directory on server where file will be uploaded>`
