### ISSUE TITLE
Ubuntu MySQL Installation clarification

### ISSUE THREAD

**Issue by edgingtonn1** [SEA-PHAGES/pdm_utils#2]
1. You may want to clarify instructions for the [Ubuntu Installation](https://github.com/SEA-PHAGES/pdm_utils/blob/master/docs/source/installation.rst), since `sudo apt-get install mysql-server` does not always result in an installation that prompts for a new password for the MySQL 'root' user. Instructions for root login without a password, setting the root password, and creating new user accounts would be helpful. For example for MySQL 8.0: 
`sudo mysql -u root --skip-password
ALTER USER 'root'@'localhost' IDENTIFIED BY 'newpassword';`
`#Create a new user account with the name 'newuser' with all privileges:`
`sudo mysql -u root -p`
`CREATE USER 'newuser'@'localhost'
  IDENTIFIED BY 'newpassword';`
`GRANT ALL
  ON *.*
  TO 'newuser'@'localhost'
  WITH GRANT OPTION;`
`FLUSH PRIVILEGES; `

2. It is not clear whether it is recommended that the [MySQL Apt repository](https://dev.mysql.com/downloads/repo/apt/) should be added before installation with `sudo apt-get install mysql-server`.
3. In some cases the `sudo apt-get install mysql-server` command results in the installation of MySQL server 8.0 (rather than 5.7), so the instructions might be clarified to show how to specifically download the 5.7 version. _However, so far running `pdm_utils` on MySQL 8.0 has not resulted in any issues._

**Comment by tmavrich** [comment]
Thanks for the suggestions. We've improved documentation for Ubuntu installation and have tried to clarify all of these points.
