### ISSUE TITLE
Genome object's 'cds_features' attribute list issue

### ISSUE THREAD

**Issue by edgingtonn1** [SEA-PHAGES/pdm_utils#3]
In [pdm_utils Cds data](https://github.com/SEA-PHAGES/pdm_utils/blob/master/docs/source/applications/library.rst#access-pdm_utils-cds-data), these don't seem to work:
`cds54.start`
`cds54.stop`
`cds54.orientation`
***ERROR:**    `AttributeError: 'Cds' object has no attribute 'orientation'

**Comment by tmavrich** [comment]
These three attributes were recently renamed to exactly mirror their corresponding columns in the gene table, and the documentation had been updated to reflect the changes, but the version on PyPI (0.0.16) had not been updated. The newest version (0.0.17) is now available on PyPI. If you update pdm_utils on your end, the problem should now be fixed.

**Comment by edgingtonn1** [comment]
Excellent--Thanks!
