### ISSUE TITLE
cdd pipeline gets stuck on MacOS

### ISSUE THREAD

**Issue by tmavrich** [SEA-PHAGES/pdm_utils#4]
Trying to run cdd pipeline on Mac. It seems to be repeatedly calling main() in the subprocesses for some reason.

Here's the command:

(pdm_utils-dev) hatfull-ghosh:sqla Hatfull_Lab$ python3 ~/scripts_git/pdm_utils/src/pdm_utils/__main__.py cdd Actinobacteriophage ~/ncbi_cdd/Cdd/

Here's the output:

Detected MacOS operating system...
Found rpsblast binary at '/usr/local/ncbi/blast/bin/rpsblast'...
MySQL username: 
MySQL password: 
90 genes to search for conserved domains...
Detected MacOS operating system...
Detected MacOS operating system...
Detected MacOS operating system...
Detected MacOS operating system...
Detected MacOS operating system...
Detected MacOS operating system...
Found rpsblast binary at '/usr/local/ncbi/blast/bin/rpsblast'...
Found rpsblast binary at '/usr/local/ncbi/blast/bin/rpsblast'...
Found rpsblast binary at '/usr/local/ncbi/blast/bin/rpsblast'...
Found rpsblast binary at '/usr/local/ncbi/blast/bin/rpsblast'...
Found rpsblast binary at '/usr/local/ncbi/blast/bin/rpsblast'...
Found rpsblast binary at '/usr/local/ncbi/blast/bin/rpsblast'...
Detected MacOS operating system...
Found rpsblast binary at '/usr/local/ncbi/blast/bin/rpsblast'...
MySQL username: MySQL username: MySQL username: MySQL username: MySQL username: MySQL username: MySQL username: Detected MacOS operating system...
Found rpsblast binary at '/usr/local/ncbi/blast/bin/rpsblast'...
MySQL username:

**Comment by tmavrich** [comment]
Strange error associated with some but not all MacOS machines. Bug has been fixed by specifying mp should use "fork".

**Comment by chg60** [comment]
Good practice to also note the commit that fixed the issue - in this case:

28f361b2d635fa69b72ecd2ca00c1105cbb5578c
