### ISSUE TITLE
MMSeqs error - unable to find output file

### ISSUE THREAD

**Issue by tmavrich** [SEA-PHAGES/pdm_utils#5]
Installed MMSeqs on MacOS. Tried to run it on a database using latest commit on master branch:

python3 ~/scripts_git/pdm_utils/src/pdm_utils/__main__.py phamerate Actinobacteriophage --steps 2

Pipeline crashed with this error:

Beginning to parse mmseqs output...
Traceback (most recent call last):
  File "/Users/Hatfull_Lab/scripts_git/pdm_utils/src/pdm_utils/__main__.py", line 4, in <module>
    run.main(sys.argv)
  File "/Users/Hatfull_Lab/scripts_git/pdm_utils/src/pdm_utils/run.py", line 71, in main
    phamerate.main(unparsed_args[unparsed_args.index("phamerate") + 1:])
  File "/Users/Hatfull_Lab/scripts_git/pdm_utils/src/pdm_utils/pipelines/phamerate.py", line 111, in main
    new_phams = parse_output(program)
  File "/Users/Hatfull_Lab/scripts_git/pdm_utils/src/pdm_utils/functions/phameration.py", line 251, in parse_output
    with open(f"{dir}/output.txt", "r") as fh:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/phamerate/output.txt'

Here is a listing of file contents in /tmp/phamerate:

ls -lta /tmp/phamerate/

total 221848
-rw-r--r--   1 Hatfull_Lab  wheel         4 Jan 28 14:36 output.txt.dbtype
drwxr-xr-x  26 Hatfull_Lab  wheel       832 Jan 28 14:36 .
-rw-r--r--   1 Hatfull_Lab  wheel    469466 Jan 28 14:36 output.txt.index
-rw-r--r--   1 Hatfull_Lab  wheel   4832297 Jan 28 14:36 output.txt.7
-rw-r--r--   1 Hatfull_Lab  wheel   4535338 Jan 28 14:36 output.txt.6
-rw-r--r--   1 Hatfull_Lab  wheel   3811765 Jan 28 14:36 output.txt.5
-rw-r--r--   1 Hatfull_Lab  wheel   4590493 Jan 28 14:36 output.txt.4
-rw-r--r--   1 Hatfull_Lab  wheel   3823859 Jan 28 14:36 output.txt.3
-rw-r--r--   1 Hatfull_Lab  wheel   4740746 Jan 28 14:36 output.txt.2
-rw-r--r--   1 Hatfull_Lab  wheel   4751525 Jan 28 14:36 output.txt.1
-rw-r--r--   1 Hatfull_Lab  wheel   3279268 Jan 28 14:36 output.txt.0
-rw-r--r--   1 Hatfull_Lab  wheel         4 Jan 28 14:36 clusterDB.dbtype
-rw-r--r--   1 Hatfull_Lab  wheel    391143 Jan 28 14:36 clusterDB.index
-rw-r--r--   1 Hatfull_Lab  wheel    937217 Jan 28 14:36 clusterDB
drwxr-xr-x  41 Hatfull_Lab  wheel      1312 Jan 28 14:36 16337895337158338783
lrwxr-xr-x   1 Hatfull_Lab  wheel        20 Jan 28 14:34 latest -> 16337895337158338783
-rw-r--r--   1 Hatfull_Lab  wheel   3378244 Jan 28 14:34 sequenceDB.lookup
-rw-r--r--   1 Hatfull_Lab  wheel   2445572 Jan 28 14:34 sequenceDB_h.index
-rw-r--r--   1 Hatfull_Lab  wheel   2716313 Jan 28 14:34 sequenceDB.index
-rw-r--r--   1 Hatfull_Lab  wheel         4 Jan 28 14:34 sequenceDB.dbtype
-rw-r--r--   1 Hatfull_Lab  wheel  32167034 Jan 28 14:34 sequenceDB
-rw-r--r--   1 Hatfull_Lab  wheel         4 Jan 28 14:34 sequenceDB_h.dbtype
-rw-r--r--   1 Hatfull_Lab  wheel   2319642 Jan 28 14:34 sequenceDB_h
-rw-r--r--   1 Hatfull_Lab  wheel        14 Jan 28 14:34 sequenceDB.source
-rw-r--r--   1 Hatfull_Lab  wheel  34340462 Jan 28 14:34 input.fasta
drwxrwxrwt  10 root         wheel       320 Jan 28 14:34 ..

**Comment by chg60** [comment]
fixed as of commit eea8905c297dbd266feb22d76ebedac3f430c2a2
