### ISSUE TITLE
integration tests do not remove test files afterwards

### ISSUE THREAD

**Issue by tmavrich** [SEA-PHAGES/pdm_utils#6]
integration_heavy tests create error.log and formatdb.log files in the src/ directory. these need to be removed during teardown().

**Comment by chg60** [comment]
fixed as of d7011c9c422c22648fc72368633657a934d69902

formatdb.log was removed by adding "-l {temp_dir}/formatdb.log" to the command that builds the blast database - now this log file is placed in the temporary directory, and deleted on subsequent runs of pham assembly.

Sadly it's not apparent that a similar trick can be used with blastclust for error.log.  Instead, an if test is done during teardown that deletes the file from the directory where the tests were run from (e.g. src/) if it is found.
